#!/bin/bash
# generate-docs-index.sh — Auto-generate documentation index for .agent/
# Usage: bash .agent/scripts/generate-docs-index.sh [--check]
# --check: Only verify if index is up-to-date (exit 1 if stale)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$AGENT_DIR/docs-index.md"
CHECK_MODE=false

[[ "${1:-}" == "--check" ]] && CHECK_MODE=true

# --- Helper functions ---

extract_frontmatter_description() {
    local file="$1"
    # Extract description from YAML frontmatter (between --- markers)
    awk '
        /^---$/ { if (in_fm) exit; in_fm=1; next }
        in_fm && /^description:/ {
            sub(/^description:[[:space:]]*/, "");
            print;
            exit
        }
    ' "$file" 2>/dev/null || echo ""
}

extract_script_description() {
    local file="$1"
    # Find first comment line with actual description (skip shebang, separators)
    awk '
        NR == 1 { next }  # skip shebang
        /^#[[:space:]]*$/ { next }  # skip empty comments
        /^#[[:space:]]*=+/ { next }  # skip separator lines
        /^#[[:space:]]*-+/ { next }  # skip separator lines
        /^#/ {
            sub(/^#[[:space:]]*/, "")
            # Remove emoji prefix for cleaner output
            sub(/^[^a-zA-Zа-яА-Я]*/, "")
            print
            exit
        }
    ' "$file" 2>/dev/null || echo ""
}

get_file_date() {
    local file="$1"
    stat -f "%Sm" -t "%Y-%m-%d" "$file" 2>/dev/null || stat -c "%y" "$file" 2>/dev/null | cut -d' ' -f1
}

# --- Generate index content ---

generate_index() {
    cat << 'HEADER'
# .agent/ Documentation Index

> Auto-generated by `generate-docs-index.sh`. Do not edit manually.

HEADER

    # --- Workflows ---
    echo "## Workflows"
    echo ""
    echo "| File | Description | Updated |"
    echo "|------|-------------|---------|"

    for f in "$AGENT_DIR"/workflows/*.md; do
        [[ -f "$f" ]] || continue
        name=$(basename "$f")
        desc=$(extract_frontmatter_description "$f")
        date=$(get_file_date "$f")
        echo "| [$name](workflows/$name) | $desc | $date |"
    done
    echo ""

    # --- Scripts ---
    echo "## Scripts"
    echo ""
    echo "| File | Description | Updated |"
    echo "|------|-------------|---------|"

    for f in "$AGENT_DIR"/scripts/*.sh; do
        [[ -f "$f" ]] || continue
        name=$(basename "$f")
        desc=$(extract_script_description "$f")
        date=$(get_file_date "$f")
        echo "| [$name](scripts/$name) | $desc | $date |"
    done
    echo ""

    # --- Templates ---
    if [[ -d "$AGENT_DIR/templates" ]] && ls "$AGENT_DIR"/templates/* &>/dev/null; then
        echo "## Templates"
        echo ""
        echo "| File | Updated |"
        echo "|------|---------|"

        for f in "$AGENT_DIR"/templates/*; do
            [[ -f "$f" ]] || continue
            name=$(basename "$f")
            date=$(get_file_date "$f")
            echo "| [$name](templates/$name) | $date |"
        done
        echo ""
    fi

    # --- Prompts ---
    if [[ -d "$AGENT_DIR/prompts" ]] && ls "$AGENT_DIR"/prompts/*.md &>/dev/null 2>&1; then
        echo "## Prompts"
        echo ""
        echo "| File | Description | Updated |"
        echo "|------|-------------|---------|"

        for f in "$AGENT_DIR"/prompts/*.md; do
            [[ -f "$f" ]] || continue
            name=$(basename "$f")
            desc=$(extract_frontmatter_description "$f")
            date=$(get_file_date "$f")
            echo "| [$name](prompts/$name) | $desc | $date |"
        done
        echo ""
    fi

    # --- Footer ---
    echo "---"
    echo ""
    echo "_Last generated: $(date '+%Y-%m-%d %H:%M')_"
}

# --- Main ---

if $CHECK_MODE; then
    # Check if regeneration would change anything
    NEW_CONTENT=$(generate_index)
    if [[ -f "$OUTPUT_FILE" ]]; then
        # Compare without timestamp line
        OLD_CONTENT=$(grep -v "^_Last generated:" "$OUTPUT_FILE" || true)
        NEW_COMPARE=$(echo "$NEW_CONTENT" | grep -v "^_Last generated:")

        if [[ "$OLD_CONTENT" != "$NEW_COMPARE" ]]; then
            echo "⚠️  docs-index.md is stale. Run: bash .agent/scripts/generate-docs-index.sh"
            exit 1
        fi
    else
        echo "⚠️  docs-index.md missing. Run: bash .agent/scripts/generate-docs-index.sh"
        exit 1
    fi
    echo "✅ docs-index.md is up-to-date"
    exit 0
fi

# Generate and write
generate_index > "$OUTPUT_FILE"
echo "✅ Generated $OUTPUT_FILE"
