#!/bin/bash
# ============================================================================
# 🏥 Projects Health Check
# Scans ~/projects/ and checks AI-infrastructure health for each project
# Run: daily via cron or manually
# Output: ~/.agent/health-report.md (global report)
# ============================================================================

set -e

PROJECTS_DIR="${HOME}/projects"
REPORT_FILE="${HOME}/.agent/health-report.md"
DATE=$(date '+%Y-%m-%d %H:%M')

# Ensure output directory exists
mkdir -p "$(dirname "$REPORT_FILE")"

# Counters
total=0
with_agent=0
with_hook=0
with_uncommitted=0
no_git=0

# Arrays for categorized projects
declare -a healthy_projects=()
declare -a working_projects=()
declare -a attention_projects=()

# ============================================================================
# Scan Projects
# ============================================================================

for project_path in "$PROJECTS_DIR"/*/; do
    # Skip if not a directory
    [[ ! -d "$project_path" ]] && continue
    
    project_name=$(basename "$project_path")
    ((total++))
    
    # Initialize flags
    has_agent="❌"
    has_hook="-"
    git_status="no git"
    issues=()
    
    # Check .agent/ directory
    if [[ -d "${project_path}.agent" ]]; then
        has_agent="✅"
        ((with_agent++))
        
        # Check HOOK.md (active work)
        if [[ -f "${project_path}.agent/HOOK.md" ]]; then
            has_hook="🔴 ACTIVE"
            ((with_hook++))
        fi
    else
        issues+=("No .agent/")
    fi
    
    # Check git status
    if [[ -d "${project_path}.git" ]]; then
        cd "$project_path"
        
        # Check for uncommitted changes
        if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
            git_status="⚠️ uncommitted"
            ((with_uncommitted++))
            issues+=("Uncommitted changes")
        else
            git_status="✅ clean"
        fi
        
        cd - > /dev/null
    else
        ((no_git++))
        issues+=("No git")
    fi
    
    # Categorize (3-tier model)
    # Healthy: has .agent/ + clean git
    # Working: has .agent/ + uncommitted changes  
    # Attention: no .agent/ OR no git
    if [[ -d "${project_path}.agent" && -d "${project_path}.git" ]]; then
        if [[ "$git_status" == "✅ clean" ]]; then
            healthy_projects+=("| $project_name | $has_agent | $has_hook | $git_status |")
        else
            # Has agent + git but uncommitted = Working
            working_projects+=("| $project_name | $has_hook | $git_status |")
        fi
    else
        issues_str=$(IFS=', '; echo "${issues[*]}")
        attention_projects+=("| $project_name | $issues_str |")
    fi
done

# ============================================================================
# Generate Report
# ============================================================================

cat > "$REPORT_FILE" << EOF
# 🏥 Projects Health Report

**Generated:** $DATE  
**Scanned:** \`$PROJECTS_DIR\`

---

## Summary

| Metric | Count | Percentage |
|--------|-------|------------|
| **Total projects** | $total | 100% |
| With \`.agent/\` | $with_agent | $(( total > 0 ? with_agent * 100 / total : 0 ))% |
| Active HOOKs | $with_hook | - |
| Uncommitted changes | $with_uncommitted | - |
| No git repository | $no_git | - |

---

## ✅ Healthy Projects (${#healthy_projects[@]})

| Project | .agent/ | HOOK | Git Status |
|---------|---------|------|------------|
EOF

for line in "${healthy_projects[@]}"; do
    echo "$line" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF

---

## 🔨 Working Projects (${#working_projects[@]})

| Project | HOOK | Git Status |
|---------|------|------------|
EOF

for line in "${working_projects[@]}"; do
    echo "$line" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF

---

## ⚠️ Projects Needing Attention (${#attention_projects[@]})

| Project | Issues |
|---------|--------|
EOF

for line in "${attention_projects[@]}"; do
    echo "$line" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << EOF

---

## Recommendations

EOF

if [[ $with_agent -lt $total ]]; then
    echo "- **Add .agent/ infrastructure** to $(( total - with_agent )) projects: \`/setup-ai-pipeline\`" >> "$REPORT_FILE"
fi

if [[ $with_uncommitted -gt 0 ]]; then
    echo "- **Commit or stash changes** in $with_uncommitted projects" >> "$REPORT_FILE"
fi

if [[ $with_hook -gt 0 ]]; then
    echo "- **$with_hook active HOOKs** — continue pending work with GUPP" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by \`projects-health-check.sh\`*" >> "$REPORT_FILE"

# ============================================================================
# Generate JSON for Dashboard
# ============================================================================

DASHBOARD_DIR="$(dirname "$0")/../dashboard"
JSON_FILE="$DASHBOARD_DIR/data.json"

if [[ -d "$DASHBOARD_DIR" ]]; then
    # Build healthy projects JSON array
    healthy_json="["
    first=true
    for project_path in "$PROJECTS_DIR"/*/; do
        [[ ! -d "$project_path" ]] && continue
        project_name=$(basename "$project_path")
        
        # Check if healthy (has .agent/, clean git)
        if [[ -d "${project_path}.agent" && -d "${project_path}.git" ]]; then
            cd "$project_path"
            if [[ -z $(git status --porcelain 2>/dev/null) ]]; then
                has_hook="false"
                [[ -f "${project_path}.agent/HOOK.md" ]] && has_hook="true"
                
                $first || healthy_json+=","
                first=false
                healthy_json+="{\"name\":\"$project_name\",\"agent\":true,\"hook\":$has_hook,\"gitStatus\":\"clean\"}"
            fi
            cd - > /dev/null
        fi
    done
    healthy_json+="]"

    # Build working projects JSON array (has .agent/ but uncommitted changes)
    working_json="["
    first=true
    for project_path in "$PROJECTS_DIR"/*/; do
        [[ ! -d "$project_path" ]] && continue
        project_name=$(basename "$project_path")
        
        if [[ -d "${project_path}.agent" && -d "${project_path}.git" ]]; then
            cd "$project_path"
            if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
                has_hook="false"
                [[ -f "${project_path}.agent/HOOK.md" ]] && has_hook="true"
                
                $first || working_json+=","
                first=false
                working_json+="{\"name\":\"$project_name\",\"agent\":true,\"hook\":$has_hook,\"gitStatus\":\"uncommitted\"}"
            fi
            cd - > /dev/null
        fi
    done
    working_json+="]"

    # Build attention projects JSON array (no .agent/ OR no .git/)
    attention_json="["
    first=true
    for project_path in "$PROJECTS_DIR"/*/; do
        [[ ! -d "$project_path" ]] && continue
        project_name=$(basename "$project_path")
        issues="["
        has_issues=false
        
        if [[ ! -d "${project_path}.agent" ]]; then
            issues+="\"No .agent/\""
            has_issues=true
        fi
        
        if [[ ! -d "${project_path}.git" ]]; then
            $has_issues && issues+=","
            issues+="\"No git\""
            has_issues=true
        fi
        
        issues+="]"
        
        if $has_issues; then
            $first || attention_json+=","
            first=false
            attention_json+="{\"name\":\"$project_name\",\"issues\":$issues}"
        fi
    done
    attention_json+="]"

    # Build recommendations JSON
    recs_json="["
    first=true
    if [[ $with_agent -lt $total ]]; then
        recs_json+="{\"text\":\"Add .agent/ infrastructure to $(( total - with_agent )) projects\",\"command\":\"/setup-ai-pipeline\"}"
        first=false
    fi
    if [[ $with_uncommitted -gt 0 ]]; then
        $first || recs_json+=","
        recs_json+="{\"text\":\"Commit or stash changes in $with_uncommitted projects\",\"command\":null}"
        first=false
    fi
    if [[ $with_hook -gt 0 ]]; then
        $first || recs_json+=","
        recs_json+="{\"text\":\"$with_hook active HOOK(s) — continue pending work with GUPP\",\"command\":null}"
    fi
    recs_json+="]"

    # Write JSON file
    cat > "$JSON_FILE" <<JSONEOF
{
    "generated": "$DATE",
    "scannedPath": "$PROJECTS_DIR",
    "summary": {
        "total": $total,
        "withAgent": $with_agent,
        "activeHooks": $with_hook,
        "uncommitted": $with_uncommitted,
        "noGit": $no_git
    },
    "healthyProjects": $healthy_json,
    "workingProjects": $working_json,
    "attentionProjects": $attention_json,
    "recommendations": $recs_json
}
JSONEOF
    
    echo "📊 Dashboard data: $JSON_FILE"
fi

# ============================================================================
# Output to terminal
# ============================================================================

echo "✅ Health report generated: $REPORT_FILE"
echo ""
echo "📊 Summary:"
echo "   Total: $total | .agent/: $with_agent | HOOKs: $with_hook | Uncommitted: $with_uncommitted"
