#!/bin/bash

# =============================================================================
# Sets up unified AI agent infrastructure with Single Source of Truth
# Usage: setup-ai-infrastructure.sh [project-path] [--dry-run] [--force]
# =============================================================================

set -e

# Source utilities
source "$(dirname "$0")/utils.sh"

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="$(dirname "$SCRIPT_DIR")/templates"
DATE=$(date +%Y-%m-%d)

# Flags
DRY_RUN=false
FORCE=false
TARGET_DIR=""

# Parse arguments - handle flags and path in any order
for arg in "$@"; do
    case $arg in
        --dry-run) DRY_RUN=true ;;
        --force) FORCE=true ;;
        --help|-h)
            echo "Usage: setup-ai-infrastructure.sh [project-path] [--dry-run] [--force]"
            echo ""
            echo "Options:"
            echo "  project-path   Target project directory (default: current)"
            echo "  --dry-run      Preview changes without applying"
            echo "  --force        Overwrite existing files"
            exit 0
            ;;
        *)
            # Not a flag, treat as path
            if [ -z "$TARGET_DIR" ]; then
                TARGET_DIR="$arg"
            fi
            ;;
    esac
done

# Default to current directory if no path provided
TARGET_DIR="${TARGET_DIR:-$(pwd)}"
PROJECT_NAME=$(basename "$TARGET_DIR")

echo -e "${CYAN}🏗️ AI Infrastructure Setup${NC}"
echo -e "   Target: ${BLUE}$TARGET_DIR${NC}"
echo ""

# Verify target is a git repo
if [ ! -d "$TARGET_DIR/.git" ]; then
    log_fail "Not a git repository: $TARGET_DIR"
    echo "   Run: git init"
    exit 1
fi

# Create directories
create_dir() {
    local dir="$1"
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY]${NC} mkdir -p $dir"
    else
        mkdir -p "$dir"
        log_pass "Created: $dir"
    fi
}

# Create file from template
create_from_template() {
    local template="$1"
    local target="$2"
    local force="${3:-false}"
    
    if [ -f "$target" ] && [ "$force" = "false" ]; then
        log_warn "Skipped (exists): $target"
        return
    fi
    
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY]${NC} Create: $target"
    else
        if [ -f "$template" ]; then
            sed -e "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" \
                -e "s/{{DATE}}/$DATE/g" \
                -e "s/{{PROJECT_DESCRIPTION}}/TODO: Add one-liner description/g" \
                -e "s/{{TECH_STACK}}/TODO: Add tech stack/g" \
                "$template" > "$target"
        else
            cat > "$target"
        fi
        log_pass "Created: $target"
    fi
}

# Create empty markdown with header
create_empty_doc() {
    local target="$1"
    local title="$2"
    
    if [ -f "$target" ]; then
        log_warn "Skipped (exists): $target"
        return
    fi
    
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY]${NC} Create: $target"
    else
        cat > "$target" << EOF
# $title

> TODO: Add content

---

*Last updated: $DATE*
EOF
        log_pass "Created: $target"
    fi
}

log_header "📁 Creating directory structure"
create_dir "$TARGET_DIR/.agent"
create_dir "$TARGET_DIR/.agent/docs"
create_dir "$TARGET_DIR/.agent/workflows"
create_dir "$TARGET_DIR/.agent/scripts"
create_dir "$TARGET_DIR/.agent/templates"
create_dir "$TARGET_DIR/.agent/prompts"
echo ""

log_header "📄 Creating main context file"
if [ -f "$TEMPLATES_DIR/MAIN.md.template" ]; then
    create_from_template "$TEMPLATES_DIR/MAIN.md.template" "$TARGET_DIR/.agent/MAIN.md" $FORCE
else
    # Inline template if templates not available
    if [ ! -f "$TARGET_DIR/.agent/MAIN.md" ] || [ "$FORCE" = "true" ]; then
        if $DRY_RUN; then
            echo -e "  ${YELLOW}[DRY]${NC} Create: $TARGET_DIR/.agent/MAIN.md"
        else
            cat > "$TARGET_DIR/.agent/MAIN.md" << 'MAINEOF'
# PROJECT_NAME — AI Agent Context

> Single Source of Truth for all AI agents

## 🎯 Project Purpose

**One-liner:** TODO: Add description

**Tech Stack:** TODO: Add stack

## 🪝 GUPP: Guaranteed Uninterrupted Progress

### FIRST ACTION — Always:
```bash
cat .agent/HOOK.md 2>/dev/null | head -30
```

| Status | Action |
|--------|--------|
| **ACTIVE 🔴** | Execute CURRENT molecule. No new work. |
| **IDLE ⚪** | Free to accept new tasks. |

## 📏 Thresholds

| Condition | Action |
|-----------|--------|
| Task > 3 files | `/decompose` first |
| 10+ tool calls | Consider `/handoff` |
| 5+ files changed | Commit immediately |

## 🚫 Never

- ❌ Ignore existing HOOK.md
- ❌ Edit 5+ files without commit
- ❌ Skip handoff when limit approaching

---

*Generated by setup-ai-infrastructure.sh*
MAINEOF
            sed -i '' "s/PROJECT_NAME/$PROJECT_NAME/g" "$TARGET_DIR/.agent/MAIN.md" 2>/dev/null || \
            sed -i "s/PROJECT_NAME/$PROJECT_NAME/g" "$TARGET_DIR/.agent/MAIN.md"
                log_pass "Created: $TARGET_DIR/.agent/MAIN.md"
        fi
    else
        log_warn "Skipped (exists): $TARGET_DIR/.agent/MAIN.md"
    fi
fi
echo ""

log_header "🔗 Creating redirect files"

# =============================================================================
# 🧠 SMART CONFLICT DETECTION
# =============================================================================

# Check if file has real content (not a redirect stub)
has_real_content() {
    local file="$1"
    local min_lines=15  # Redirect stubs are ~5-10 lines
    
    if [ ! -f "$file" ]; then
        echo "empty"
        return
    fi
    
    local line_count=$(wc -l < "$file" | tr -d ' ')
    local has_redirect=$(grep -c "→ .agent/MAIN.md" "$file" 2>/dev/null | tr -d ' \n' || echo "0")
    
    if [ "$has_redirect" -gt 0 ]; then
        echo "redirect"
    elif [ "$line_count" -gt "$min_lines" ]; then
        echo "content"
    else
        echo "minimal"
    fi
}

# Smart backup and migrate content
smart_migrate() {
    local file="$1"
    local backup_name="$2"
    local backup_path="$TARGET_DIR/.agent/$backup_name"
    
    if $DRY_RUN; then
        echo -e "  ${CYAN}[SMART]${NC} Would backup: $file → $backup_path"
        echo -e "  ${CYAN}[SMART]${NC} Would merge content into .agent/MAIN.md"
    else
        cp "$file" "$backup_path"
        log_pass "Backed up: $file → $backup_path"
        
        # Append content to MAIN.md if it exists
        if [ -f "$TARGET_DIR/.agent/MAIN.md" ]; then
            echo "" >> "$TARGET_DIR/.agent/MAIN.md"
            echo "---" >> "$TARGET_DIR/.agent/MAIN.md"
            echo "" >> "$TARGET_DIR/.agent/MAIN.md"
            echo "## 📥 Migrated from $(basename $file)" >> "$TARGET_DIR/.agent/MAIN.md"
            echo "" >> "$TARGET_DIR/.agent/MAIN.md"
            cat "$file" >> "$TARGET_DIR/.agent/MAIN.md"
            log_pass "Content merged into .agent/MAIN.md"
        fi
    fi
}

# CLAUDE.md - SMART handling
CLAUDE_STATUS=$(has_real_content "$TARGET_DIR/CLAUDE.md")

if [ "$CLAUDE_STATUS" = "content" ]; then
    log_warn "Found CLAUDE.md with real content (${CLAUDE_STATUS})"
    smart_migrate "$TARGET_DIR/CLAUDE.md" "CLAUDE_MIGRATED.md"
    # Now create redirect
    if ! $DRY_RUN; then
        cat > "$TARGET_DIR/CLAUDE.md" << 'EOF'
# CLAUDE.md → .agent/MAIN.md

> **Redirect.** The actual agent context lives in `.agent/MAIN.md`.

```bash
cat .agent/MAIN.md
```

See [.agent/MAIN.md](.agent/MAIN.md) for full context.

---
*Original content migrated to .agent/CLAUDE_MIGRATED.md*
EOF
        log_pass "Created: $TARGET_DIR/CLAUDE.md (redirect + migration note)"
    fi
elif [ "$CLAUDE_STATUS" = "redirect" ]; then
    log_pass "CLAUDE.md already a redirect — skipped"
elif [ ! -f "$TARGET_DIR/CLAUDE.md" ] || [ "$FORCE" = "true" ]; then
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY]${NC} Create: $TARGET_DIR/CLAUDE.md"
    else
        cat > "$TARGET_DIR/CLAUDE.md" << 'EOF'
# CLAUDE.md → .agent/MAIN.md

> **Redirect.** The actual agent context lives in `.agent/MAIN.md`.

```bash
cat .agent/MAIN.md
```

See [.agent/MAIN.md](.agent/MAIN.md) for full context.
EOF
        log_pass "Created: $TARGET_DIR/CLAUDE.md (redirect)"
    fi
fi

# AGENTS.md - SMART handling
AGENTS_STATUS=$(has_real_content "$TARGET_DIR/AGENTS.md")

if [ "$AGENTS_STATUS" = "content" ]; then
    log_warn "Found AGENTS.md with real content"
    smart_migrate "$TARGET_DIR/AGENTS.md" "AGENTS_MIGRATED.md"
    if ! $DRY_RUN; then
        cat > "$TARGET_DIR/AGENTS.md" << 'EOF'
# AGENTS.md → .agent/MAIN.md

> **Redirect for Codex.** See `.agent/MAIN.md` for context.

```bash
cat .agent/MAIN.md
```

---
*Original content migrated to .agent/AGENTS_MIGRATED.md*
EOF
        log_pass "Created: $TARGET_DIR/AGENTS.md (redirect + migration note)"
    fi
elif [ "$AGENTS_STATUS" = "redirect" ]; then
    log_pass "AGENTS.md already a redirect — skipped"
elif [ ! -f "$TARGET_DIR/AGENTS.md" ] || [ "$FORCE" = "true" ]; then
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY]${NC} Create: $TARGET_DIR/AGENTS.md"
    else
        cat > "$TARGET_DIR/AGENTS.md" << 'EOF'
# AGENTS.md → .agent/MAIN.md

> **Redirect for Codex.** See `.agent/MAIN.md` for context.

```bash
cat .agent/MAIN.md
```
EOF
        log_pass "Created: $TARGET_DIR/AGENTS.md (redirect)"
    fi
fi

# .cursorrules - SMART handling
CURSORRULES_STATUS=$(has_real_content "$TARGET_DIR/.cursorrules")

if [ "$CURSORRULES_STATUS" = "content" ]; then
    log_warn "Found .cursorrules with real content"
    smart_migrate "$TARGET_DIR/.cursorrules" "cursorrules_MIGRATED.txt"
    if ! $DRY_RUN; then
        cat > "$TARGET_DIR/.cursorrules" << 'EOF'
# .cursorrules → .agent/MAIN.md

Read .agent/MAIN.md for full project context.

---
Original content migrated to .agent/cursorrules_MIGRATED.txt
EOF
        log_pass "Created: $TARGET_DIR/.cursorrules (redirect + migration note)"
    fi
elif [ "$CURSORRULES_STATUS" = "redirect" ]; then
    log_pass ".cursorrules already a redirect — skipped"
elif [ ! -f "$TARGET_DIR/.cursorrules" ] || [ "$FORCE" = "true" ]; then
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY]${NC} Create: $TARGET_DIR/.cursorrules"
    else
        cat > "$TARGET_DIR/.cursorrules" << 'EOF'
# .cursorrules → .agent/MAIN.md

Read .agent/MAIN.md for full project context.
EOF
        log_pass "Created: $TARGET_DIR/.cursorrules (redirect)"
    fi
fi
echo ""

log_header "📚 Creating docs stubs"
create_empty_doc "$TARGET_DIR/.agent/docs/architecture.md" "Architecture"
create_empty_doc "$TARGET_DIR/.agent/docs/conventions.md" "Conventions"
create_empty_doc "$TARGET_DIR/.agent/docs/stack.md" "Tech Stack"
echo ""

log_header "🪝 Installing git hooks"
if [ -f "$SCRIPT_DIR/install-hooks.sh" ]; then
    if $DRY_RUN; then
        echo -e "  ${YELLOW}[DRY]${NC} Would install git hooks"
    else
        bash "$SCRIPT_DIR/install-hooks.sh" "$TARGET_DIR"
    fi
else
    log_warn "install-hooks.sh not found, skipping"
fi
echo ""

log_header "📋 Summary"
log_pass ".agent/ infrastructure created"
log_pass "MAIN.md — Single Source of Truth"
log_pass "Redirects: CLAUDE.md, AGENTS.md, .cursorrules"
log_pass "Git hooks installed"
echo ""

if $DRY_RUN; then
    echo -e "${YELLOW}⚠️  Dry run — no files were created${NC}"
    echo -e "   Remove --dry-run to apply changes"
else
    echo -e "${GREEN}✅ AI Infrastructure Ready!${NC}"
    echo ""
    echo -e "Next steps:"
    echo -e "  1. Edit ${CYAN}.agent/MAIN.md${NC} — add project description"
    echo -e "  2. Edit ${CYAN}.agent/docs/stack.md${NC} — document tech stack"
    echo -e "  3. Commit: ${CYAN}git add .agent/ CLAUDE.md AGENTS.md .cursorrules && git commit -m 'Add AI infrastructure'${NC}"
fi
